### ISSUE TITLE
set of agc fails

### ISSUE THREAD

**Issue by hemna** [IW0HDV/airspyhf#2]
After succesfuly building everything from the 'tools' branch, I try and run airspyhf_rx and it fails with an error of setting the hf agc.

```
root@airspy:~/openwebrx# airspyhf_info 
AirSpy HF library version: 1.1.5

S/N: 0xC852948094343FFC
Part ID: 0x00000001
Firmware Version: R1.00.00
Available sample rate: 768 kS/s

root@airspy:~/openwebrx# airspyhf_rx -r /dev/null
Device Serial Number: 0xC852948094343FFC
airspyhf_set_hf_agc failed.
root@airspy:~/openwebrx# airspyhf_rx -r /dev/null -gon
Device Serial Number: 0xC852948094343FFC
airspyhf_set_hf_agc failed.
root@airspy:~/openwebrx# airspyhf_rx -r /dev/null -goff
Device Serial Number: 0xC852948094343FFC
airspyhf_set_hf_agc failed.
```

**Comment by amontefusco** [comment]
>>> Firmware Version: R1.00.00

Try option -z.
You have in your radio the original firmware, many commands are not implemented.
-z should allow you to run a modern library against old firmware.

**Comment by hemna** [comment]
ok that seems to have made it work.   Is there a way to make the UI work like the other sites on sdr.hu?
I don't see the dropdowns for the band selection, extensions, etc.  It seems that I can only see the center frequency.   I can make my openwebrx install public if you want to see it.

**Comment by hemna** [comment]
http://home.hemna.com:8073

**Comment by amontefusco** [comment]
I'll try to install openwebrx here, just wondering in which way the central frequency can be changed.
Probably my utility needs some rework.

**Comment by hemna** [comment]
![openwebrx](https://user-images.githubusercontent.com/672207/44281939-5fd4b580-a227-11e8-883f-7e6038c921db.png)

vs

![kiwisdr](https://user-images.githubusercontent.com/672207/44281945-64996980-a227-11e8-8b35-9b32c72c1b2c.png)

**Comment by amontefusco** [comment]
As this is an issue with opewebrx, I'll write instructions on their wiki.

**Comment by amontefusco** [comment]
The Web GUI differences that you show are attributable to a specific OpenWebSDR fork, developed by KiwiSDR's developers and found in

https://github.com/jks-prv/Beagle_SDR_GPS/tree/master/web/openwebrx

currently, this fork supports only KiwiSDR hardware, so it is unsuitable for AirspyHF.
